#!/usr/bin/python3

import sys
from os import rename, system
from subprocess import call

args = list(sys.argv)[1:]

def removeifex(name):
    if name in args:
        args.remove(name)
        return True
    return False

PROFILING = removeifex("-prof")
NO_OPT = removeifex("-noopt")

if NO_OPT and PROFILING:
    print ("Invalid argument combination: noopt and profiling!")
    sys.exit()

system("ghc Infsabot/Build.hs " + ("" if NO_OPT else "-O2") + " -rtsopts -outputdir .bin -main-is Infsabot.Build")

if PROFILING:
    system("ghc Infsabot/Build.hs -O2 -osuf p_o -prof -auto -auto-all -rtsopts -outputdir .bin -main-is Infsabot.Build")

try:
    system("rm -r .bin")
    system("mkdir bin")
except Exception as _:
    pass

try:
    rename("Infsabot/Build", "bin/Build")
except Exception as e:
    print ("BUILD FAILED")

if PROFILING:
    args += ["+RTS", "-xc", "-p", "-RTS"]

call(["./bin/Build"] + args)
